"""empty message

Revision ID: 040f334cc7f3
Revises: fc4039ca79f1
Create Date: 2019-10-21 15:16:50.925330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040f334cc7f3'
down_revision = 'fc4039ca79f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_response_statuses', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_survey_response_statuses_default'), 'survey_response_statuses', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_response_statuses_default'), table_name='survey_response_statuses')
    op.drop_column('survey_response_statuses', 'default')
    # ### end Alembic commands ###
