"""remove activity definition name is unique

Revision ID: 049b4cbce413
Revises: f4215b318a25
Create Date: 2020-10-26 14:20:33.607895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049b4cbce413'
down_revision = 'f4215b318a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_definitions_name_key', 'activity_definitions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('activity_definitions_name_key', 'activity_definitions', ['name'])
    # ### end Alembic commands ###
