"""add locations table

Revision ID: 08a7b11e1328
Revises: 8c71463655c8
Create Date: 2020-05-29 21:15:46.639353

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '08a7b11e1328'
down_revision = '8c71463655c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('position_accuracy', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('altitude_accuracy', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('location_speed', sa.Float(), nullable=True),
    sa.Column('location_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True),
    sa.Column('position_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('altitude', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('altitude_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('heading', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('location_speed', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('location_dt', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_locations_version_end_transaction_id'), 'locations_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_locations_version_operation_type'), 'locations_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_locations_version_transaction_id'), 'locations_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_version_last_login_location_coordinates', 'users_version', ['last_login_location_coordinates'], unique=False)
    op.create_index('idx_users_last_login_location_coordinates', 'users', ['last_login_location_coordinates'], unique=False)
    op.create_index('idx_survey_responses_version_updated_location_coordinates', 'survey_responses_version', ['updated_location_coordinates'], unique=False)
    op.create_index('idx_survey_responses_version_created_location_coordinates', 'survey_responses_version', ['created_location_coordinates'], unique=False)
    op.create_index('idx_survey_responses_updated_location_coordinates', 'survey_responses', ['updated_location_coordinates'], unique=False)
    op.create_index('idx_survey_responses_created_location_coordinates', 'survey_responses', ['created_location_coordinates'], unique=False)
    op.create_index('idx_cases_version_updated_location_coordinates', 'cases_version', ['updated_location_coordinates'], unique=False)
    op.create_index('idx_cases_version_created_location_coordinates', 'cases_version', ['created_location_coordinates'], unique=False)
    op.create_index('idx_cases_updated_location_coordinates', 'cases', ['updated_location_coordinates'], unique=False)
    op.create_index('idx_cases_created_location_coordinates', 'cases', ['created_location_coordinates'], unique=False)
    op.drop_index(op.f('ix_locations_version_transaction_id'), table_name='locations_version')
    op.drop_index(op.f('ix_locations_version_operation_type'), table_name='locations_version')
    op.drop_index(op.f('ix_locations_version_end_transaction_id'), table_name='locations_version')
    op.drop_table('locations_version')
    op.drop_table('locations')
    # ### end Alembic commands ###
