"""add user class to continuum

Revision ID: 096b6f6fa1c4
Revises: f40188a7367b
Create Date: 2019-12-18 05:45:18.731720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096b6f6fa1c4'
down_revision = 'f40188a7367b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_column('transaction', 'user_id')
    # ### end Alembic commands ###
