"""add case and case defn required for acts and act defs

Revision ID: 0de2fad69edb
Revises: 6982a742d3f1
Create Date: 2020-10-06 17:45:34.720213

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0de2fad69edb'
down_revision = '6982a742d3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'case_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('activity_definitions', 'case_definition_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_definitions', 'case_definition_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('activities', 'case_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
