"""drop delete log

Revision ID: 127fac88103d
Revises: 99ddf08500e5
Create Date: 2019-12-18 07:07:23.703364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '127fac88103d'
down_revision = '99ddf08500e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deleted_object_log_deleted_at', table_name='deleted_object_log')
    op.drop_table('deleted_object_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_object_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_object_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('deleted_object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name='deleted_object_log_deleted_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deleted_object_log_pkey')
    )
    op.create_index('ix_deleted_object_log_deleted_at', 'deleted_object_log', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
