"""make activity_definitions.case_definition_id not null

Revision ID: 1eca38cf9e10
Revises: 57a2432f17c1
Create Date: 2020-09-23 17:35:25.341249

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1eca38cf9e10'
down_revision = '57a2432f17c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_definitions', 'case_definition_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_definitions', 'case_definition_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
