"""add case definition models

Revision ID: 3d9af39c056b
Revises: bf576353bfa4
Create Date: 2019-12-10 07:35:22.300528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9af39c056b'
down_revision = 'bf576353bfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_case_definitions_created_at'), 'case_definitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_definitions_updated_at'), 'case_definitions', ['updated_at'], unique=False)
    op.create_table('case_definition_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_definition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_definition_id'], ['case_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('case_definitions_surveys',
    sa.Column('case_definition_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_definition_id'], ['case_definitions.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_definitions_surveys')
    op.drop_table('case_definition_documents')
    op.drop_index(op.f('ix_case_definitions_updated_at'), table_name='case_definitions')
    op.drop_index(op.f('ix_case_definitions_created_at'), table_name='case_definitions')
    op.drop_table('case_definitions')
    # ### end Alembic commands ###
