"""add color to users

Revision ID: 3f78d37b9b21
Revises: e6d95b2c7791
Create Date: 2020-04-08 05:02:09.490107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f78d37b9b21'
down_revision = 'e6d95b2c7791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color', sa.String(length=16), nullable=True))
    op.add_column('users_version', sa.Column('color', sa.String(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_version', 'color')
    op.drop_column('users', 'color')
    # ### end Alembic commands ###
