"""remove uniqueness of custom field names

Revision ID: 4c04df3066b9
Revises: a559e585c396
Create Date: 2020-05-11 15:52:40.152718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c04df3066b9'
down_revision = 'a559e585c396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_fields', 'model_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_custom_fields_name', table_name='custom_fields')
    op.create_index(op.f('ix_custom_fields_name'), 'custom_fields', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_fields_name'), table_name='custom_fields')
    op.create_index('ix_custom_fields_name', 'custom_fields', ['name'], unique=True)
    op.alter_column('custom_fields', 'model_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
