"""empty message

Revision ID: 4f62eb781f6b
Revises: d5193691ddb4
Create Date: 2020-02-11 18:01:34.212683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f62eb781f6b'
down_revision = 'd5193691ddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_files_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('url', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_case_files_version_created_at'), 'case_files_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_files_version_end_transaction_id'), 'case_files_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_case_files_version_operation_type'), 'case_files_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_case_files_version_transaction_id'), 'case_files_version', ['transaction_id'], unique=False)
    op.create_table('case_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_created_at'), 'case_files', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_files_created_at'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_case_files_version_transaction_id'), table_name='case_files_version')
    op.drop_index(op.f('ix_case_files_version_operation_type'), table_name='case_files_version')
    op.drop_index(op.f('ix_case_files_version_end_transaction_id'), table_name='case_files_version')
    op.drop_index(op.f('ix_case_files_version_created_at'), table_name='case_files_version')
    op.drop_table('case_files_version')
    # ### end Alembic commands ###
