"""empty message

Revision ID: 514e22928bcc
Revises: 4f62eb781f6b
Create Date: 2020-02-18 06:56:13.069695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514e22928bcc'
down_revision = '4f62eb781f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('original_filename', sa.Text(), nullable=True))
    op.add_column('case_files', sa.Column('remote_filename', sa.Text(), nullable=True))
    op.drop_column('case_files', 'filename')
    op.drop_column('case_files', 'url')
    op.add_column('case_files_version', sa.Column('original_filename', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('case_files_version', sa.Column('remote_filename', sa.Text(), autoincrement=False, nullable=True))
    op.drop_column('case_files_version', 'filename')
    op.drop_column('case_files_version', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files_version', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('case_files_version', sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('case_files_version', 'remote_filename')
    op.drop_column('case_files_version', 'original_filename')
    op.add_column('case_files', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('case_files', sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('case_files', 'remote_filename')
    op.drop_column('case_files', 'original_filename')
    # ### end Alembic commands ###
