"""add pk to case definitions surveys table

Revision ID: 525d54d17131
Revises: b7e0e9a545ea
Create Date: 2019-12-24 16:31:10.580530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d54d17131'
down_revision = 'b7e0e9a545ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_case_definitions_surveys_case_definition_id'), 'case_definitions_surveys', ['case_definition_id'], unique=False)
    op.create_index(op.f('ix_case_definitions_surveys_survey_id'), 'case_definitions_surveys', ['survey_id'], unique=False)
    op.create_index(op.f('ix_case_definitions_surveys_version_case_definition_id'), 'case_definitions_surveys_version', ['case_definition_id'], unique=False)
    op.create_index(op.f('ix_case_definitions_surveys_version_survey_id'), 'case_definitions_surveys_version', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_definitions_surveys_version_survey_id'), table_name='case_definitions_surveys_version')
    op.drop_index(op.f('ix_case_definitions_surveys_version_case_definition_id'), table_name='case_definitions_surveys_version')
    op.drop_index(op.f('ix_case_definitions_surveys_survey_id'), table_name='case_definitions_surveys')
    op.drop_index(op.f('ix_case_definitions_surveys_case_definition_id'), table_name='case_definitions_surveys')
    # ### end Alembic commands ###
