"""add activity definitions

Revision ID: 57a2432f17c1
Revises: 805050929ef8
Create Date: 2020-09-23 17:29:33.263810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57a2432f17c1'
down_revision = '805050929ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_definitions_version',
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('key', sa.String(), autoincrement=False, nullable=True),
                    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
                    sa.Column('case_definition_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False,
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
                    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_activity_definitions_version_created_at'), 'activity_definitions_version', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_activity_definitions_version_end_transaction_id'), 'activity_definitions_version',
                    ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_version_operation_type'), 'activity_definitions_version',
                    ['operation_type'], unique=False)
    op.create_index(op.f('ix_activity_definitions_version_transaction_id'), 'activity_definitions_version',
                    ['transaction_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_version_updated_at'), 'activity_definitions_version', ['updated_at'],
                    unique=False)
    op.create_table('activity_definitions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('case_definition_id', sa.Integer(), nullable=False),
                    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('created_by_id', sa.Integer(), nullable=False),
                    sa.Column('updated_by_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['case_definition_id'], ['case_definitions.id'], ),
                    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_activity_definitions_created_at'), 'activity_definitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_definitions_updated_at'), 'activity_definitions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_definitions_updated_at'), table_name='activity_definitions')
    op.drop_index(op.f('ix_activity_definitions_created_at'), table_name='activity_definitions')
    op.drop_table('activity_definitions')
    op.drop_index(op.f('ix_activity_definitions_version_updated_at'), table_name='activity_definitions_version')
    op.drop_index(op.f('ix_activity_definitions_version_transaction_id'), table_name='activity_definitions_version')
    op.drop_index(op.f('ix_activity_definitions_version_operation_type'), table_name='activity_definitions_version')
    op.drop_index(op.f('ix_activity_definitions_version_end_transaction_id'), table_name='activity_definitions_version')
    op.drop_index(op.f('ix_activity_definitions_version_created_at'), table_name='activity_definitions_version')
    op.drop_table('activity_definitions_version')
    # ### end Alembic commands ###
