"""add locations to case files

Revision ID: 61a072910ed4
Revises: 08a7b11e1328
Create Date: 2020-05-29 22:35:09.945956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a072910ed4'
down_revision = '08a7b11e1328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('extracted_location_id', sa.Integer(), nullable=True))
    op.add_column('case_files', sa.Column('taken_location_id', sa.Integer(), nullable=True))
    op.add_column('case_files', sa.Column('uploaded_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case_files', 'locations', ['extracted_location_id'], ['id'])
    op.create_foreign_key(None, 'case_files', 'locations', ['uploaded_location_id'], ['id'])
    op.create_foreign_key(None, 'case_files', 'locations', ['taken_location_id'], ['id'])
    op.add_column('case_files_version', sa.Column('extracted_location_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('case_files_version', sa.Column('taken_location_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('case_files_version', sa.Column('uploaded_location_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_files_version', 'uploaded_location_id')
    op.drop_column('case_files_version', 'taken_location_id')
    op.drop_column('case_files_version', 'extracted_location_id')
    op.drop_constraint(None, 'case_files', type_='foreignkey')
    op.drop_constraint(None, 'case_files', type_='foreignkey')
    op.drop_constraint(None, 'case_files', type_='foreignkey')
    op.drop_column('case_files', 'uploaded_location_id')
    op.drop_column('case_files', 'taken_location_id')
    op.drop_column('case_files', 'extracted_location_id')
    # ### end Alembic commands ###
