"""add case_id to activity model

Revision ID: 6982a742d3f1
Revises: b967c76e1d6a
Create Date: 2020-09-30 15:27:52.171212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6982a742d3f1'
down_revision = 'b967c76e1d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'cases', ['case_id'], ['id'])
    op.add_column('activities_version', sa.Column('case_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities_version', 'case_id')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'case_id')
    # ### end Alembic commands ###
