"""add activity definition documents

Revision ID: 740bd72ccc03
Revises: a30c6e4c46ce
Create Date: 2020-09-24 14:37:07.226145

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '740bd72ccc03'
down_revision = 'a30c6e4c46ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_definition_documents_version',
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
                    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
                    sa.Column('is_required', sa.Boolean(), autoincrement=False, nullable=True),
                    sa.Column('activity_definition_id', sa.Integer(), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_activity_definition_documents_version_end_transaction_id'),
                    'activity_definition_documents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_activity_definition_documents_version_operation_type'),
                    'activity_definition_documents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_activity_definition_documents_version_transaction_id'),
                    'activity_definition_documents_version', ['transaction_id'], unique=False)
    op.create_table('activity_definitions_surveys_version',
                    sa.Column('activity_definition_id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('survey_id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('activity_definition_id', 'survey_id', 'transaction_id')
                    )
    op.create_index(op.f('ix_activity_definitions_surveys_version_activity_definition_id'),
                    'activity_definitions_surveys_version', ['activity_definition_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_surveys_version_end_transaction_id'),
                    'activity_definitions_surveys_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_surveys_version_operation_type'),
                    'activity_definitions_surveys_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_activity_definitions_surveys_version_survey_id'), 'activity_definitions_surveys_version',
                    ['survey_id'], unique=False)
    op.create_index(op.f('ix_activity_definitions_surveys_version_transaction_id'),
                    'activity_definitions_surveys_version', ['transaction_id'], unique=False)
    op.create_table('activity_definition_documents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_required', sa.Boolean(), nullable=False),
                    sa.Column('activity_definition_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['activity_definition_id'], ['activity_definitions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_definition_documents')
    op.drop_index(op.f('ix_activity_definitions_surveys_version_transaction_id'),
                  table_name='activity_definitions_surveys_version')
    op.drop_index(op.f('ix_activity_definitions_surveys_version_survey_id'),
                  table_name='activity_definitions_surveys_version')
    op.drop_index(op.f('ix_activity_definitions_surveys_version_operation_type'),
                  table_name='activity_definitions_surveys_version')
    op.drop_index(op.f('ix_activity_definitions_surveys_version_end_transaction_id'),
                  table_name='activity_definitions_surveys_version')
    op.drop_index(op.f('ix_activity_definitions_surveys_version_activity_definition_id'),
                  table_name='activity_definitions_surveys_version')
    op.drop_table('activity_definitions_surveys_version')
    op.drop_index(op.f('ix_activity_definition_documents_version_transaction_id'),
                  table_name='activity_definition_documents_version')
    op.drop_index(op.f('ix_activity_definition_documents_version_operation_type'),
                  table_name='activity_definition_documents_version')
    op.drop_index(op.f('ix_activity_definition_documents_version_end_transaction_id'),
                  table_name='activity_definition_documents_version')
    op.drop_table('activity_definition_documents_version')
    # ### end Alembic commands ###
