"""empty message

Revision ID: 7a2eb67deda8
Revises: 514e22928bcc
Create Date: 2020-02-20 13:39:19.329361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2eb67deda8'
down_revision = '514e22928bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case_files', 'case_definition_documents', ['document_id'], ['id'])
    op.add_column('case_files_version', sa.Column('document_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_files_version', 'document_id')
    op.drop_constraint(None, 'case_files', type_='foreignkey')
    op.drop_column('case_files', 'document_id')
    # ### end Alembic commands ###
