"""empty message

Revision ID: 7bf425c240fc
Revises: e3df4f2cde48
Create Date: 2019-10-31 22:19:46.724466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf425c240fc'
down_revision = 'e3df4f2cde48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('surveys', sa.Column('updated_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'surveys', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'surveys', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'updated_by_id')
    op.drop_column('surveys', 'created_by_id')
    # ### end Alembic commands ###
