"""add custom_fields.selections back as type JSON

Revision ID: 8c71463655c8
Revises: e5f98a847867
Create Date: 2020-05-14 17:33:12.522529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c71463655c8'
down_revision = 'e5f98a847867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_fields', sa.Column('selections', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_fields', 'selections')
    # ### end Alembic commands ###
