"""add mongo collection name to surveys

Revision ID: 8ebc68288806
Revises: d05cc069dcef
Create Date: 2019-12-03 01:59:35.208194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebc68288806'
down_revision = 'd05cc069dcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('mongo_collection_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'mongo_collection_name')
    # ### end Alembic commands ###
