"""add versioning to case definition documents

Revision ID: 99ddf08500e5
Revises: b0ca51d0b628
Create Date: 2019-12-18 06:45:15.274770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ddf08500e5'
down_revision = 'b0ca51d0b628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_definition_documents_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('case_definition_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_case_definition_documents_version_end_transaction_id'), 'case_definition_documents_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_case_definition_documents_version_operation_type'), 'case_definition_documents_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_case_definition_documents_version_transaction_id'), 'case_definition_documents_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_definition_documents_version_transaction_id'), table_name='case_definition_documents_version')
    op.drop_index(op.f('ix_case_definition_documents_version_operation_type'), table_name='case_definition_documents_version')
    op.drop_index(op.f('ix_case_definition_documents_version_end_transaction_id'), table_name='case_definition_documents_version')
    op.drop_table('case_definition_documents_version')
    # ### end Alembic commands ###
