"""remove unique for case def doc name

Revision ID: 9a89353ce828
Revises: a477765fcd9e
Create Date: 2019-12-10 08:33:21.408842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a89353ce828'
down_revision = 'a477765fcd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('case_definition_documents_name_key', 'case_definition_documents', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('case_definition_documents_name_key', 'case_definition_documents', ['name'])
    # ### end Alembic commands ###
