"""add color to case statuses

Revision ID: a0a6f383a912
Revises: a44e24fa6b99
Create Date: 2020-11-24 19:17:50.275334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a6f383a912'
down_revision = 'a44e24fa6b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_statuses', sa.Column('color', sa.String(length=16), nullable=True))
    op.add_column('case_statuses', sa.Column('is_final', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_statuses', 'is_final')
    op.drop_column('case_statuses', 'color')
    # ### end Alembic commands ###
