"""add is_required to case definition documents

Revision ID: a477765fcd9e
Revises: 3d9af39c056b
Create Date: 2019-12-10 08:11:57.954276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a477765fcd9e'
down_revision = '3d9af39c056b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_definition_documents', sa.Column('is_required', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_definition_documents', 'is_required')
    # ### end Alembic commands ###
