"""empty message

Revision ID: aad659782f84
Revises: 7bf425c240fc
Create Date: 2019-11-12 17:57:30.231040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad659782f84'
down_revision = '7bf425c240fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('surveys', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_active = true")
    op.execute("UPDATE surveys SET is_archived = false")
    op.execute("UPDATE survey_responses SET is_archived = false")
    op.alter_column('users', 'is_active', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('surveys', 'is_archived', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('survey_responses', 'is_archived', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active', existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column('surveys', 'is_archived')
    op.drop_column('survey_responses', 'is_archived')
    # ### end Alembic commands ###
