"""add gps to responses

Revision ID: af1c146aa173
Revises: 7aa3ea85e9e6
Create Date: 2020-04-29 22:36:15.034051

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'af1c146aa173'
down_revision = '7aa3ea85e9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('created_location_altitude', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_altitude_accuracy', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_dt', sa.DateTime(), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_heading', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_position_accuracy', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('created_location_speed', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_altitude', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_altitude_accuracy', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_dt', sa.DateTime(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_heading', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_position_accuracy', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('updated_location_speed', sa.Float(), nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_altitude', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_altitude_accuracy', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_dt', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_heading', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_position_accuracy', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('created_location_speed', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_altitude', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_altitude_accuracy', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_dt', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_heading', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_position_accuracy', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('survey_responses_version', sa.Column('updated_location_speed', sa.Float(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses_version', 'updated_location_speed')
    op.drop_column('survey_responses_version', 'updated_location_position_accuracy')
    op.drop_column('survey_responses_version', 'updated_location_heading')
    op.drop_column('survey_responses_version', 'updated_location_dt')
    op.drop_column('survey_responses_version', 'updated_location_coordinates')
    op.drop_column('survey_responses_version', 'updated_location_altitude_accuracy')
    op.drop_column('survey_responses_version', 'updated_location_altitude')
    op.drop_column('survey_responses_version', 'created_location_speed')
    op.drop_column('survey_responses_version', 'created_location_position_accuracy')
    op.drop_column('survey_responses_version', 'created_location_heading')
    op.drop_column('survey_responses_version', 'created_location_dt')
    op.drop_column('survey_responses_version', 'created_location_coordinates')
    op.drop_column('survey_responses_version', 'created_location_altitude_accuracy')
    op.drop_column('survey_responses_version', 'created_location_altitude')
    op.drop_column('survey_responses', 'updated_location_speed')
    op.drop_column('survey_responses', 'updated_location_position_accuracy')
    op.drop_column('survey_responses', 'updated_location_heading')
    op.drop_column('survey_responses', 'updated_location_dt')
    op.drop_column('survey_responses', 'updated_location_coordinates')
    op.drop_column('survey_responses', 'updated_location_altitude_accuracy')
    op.drop_column('survey_responses', 'updated_location_altitude')
    op.drop_column('survey_responses', 'created_location_speed')
    op.drop_column('survey_responses', 'created_location_position_accuracy')
    op.drop_column('survey_responses', 'created_location_heading')
    op.drop_column('survey_responses', 'created_location_dt')
    op.drop_column('survey_responses', 'created_location_coordinates')
    op.drop_column('survey_responses', 'created_location_altitude_accuracy')
    op.drop_column('survey_responses', 'created_location_altitude')
    # ### end Alembic commands ###
