"""remove key from activity definitions

Revision ID: b196a337f956
Revises: 1eca38cf9e10
Create Date: 2020-09-23 19:09:56.548076

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b196a337f956'
down_revision = '1eca38cf9e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_definitions_key_key', 'activity_definitions', type_='unique')
    op.drop_column('activity_definitions', 'key')
    op.drop_column('activity_definitions_version', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_definitions_version', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('activity_definitions', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('activity_definitions_key_key', 'activity_definitions', ['key'])
    # ### end Alembic commands ###
