"""remove is_archived from case definitions

Revision ID: b335ac8b2345
Revises: 9a89353ce828
Create Date: 2019-12-12 17:21:02.872654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b335ac8b2345'
down_revision = '9a89353ce828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_definitions', 'is_archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_definitions', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
