"""add key to case definitions

Revision ID: b7e0e9a545ea
Revises: 127fac88103d
Create Date: 2019-12-23 22:47:12.677543

"""
from alembic import op
import sqlalchemy as sa
from app.models import CaseDefinition


# revision identifiers, used by Alembic.
revision = 'b7e0e9a545ea'
down_revision = '127fac88103d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_definitions', sa.Column('key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'case_definitions', ['key'])
    op.add_column('case_definitions_version', sa.Column('key', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_definitions_version', 'key')
    op.drop_constraint(None, 'case_definitions', type_='unique')
    op.drop_column('case_definitions', 'key')
    # ### end Alembic commands ###
