"""add uploaded files model

Revision ID: b967c76e1d6a
Revises: c296db97f6ec
Create Date: 2020-09-30 00:53:19.124240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b967c76e1d6a'
down_revision = 'c296db97f6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('remote_filename', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('uploaded_location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('taken_location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('extracted_location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_uploaded_files_version_created_at'), 'uploaded_files_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_version_end_transaction_id'), 'uploaded_files_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_version_operation_type'), 'uploaded_files_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_uploaded_files_version_transaction_id'), 'uploaded_files_version', ['transaction_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('remote_filename', sa.Text(), nullable=True),
    sa.Column('uploaded_location_id', sa.Integer(), nullable=True),
    sa.Column('taken_location_id', sa.Integer(), nullable=True),
    sa.Column('extracted_location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['extracted_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['taken_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_created_at'), 'uploaded_files', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_created_at'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_version_transaction_id'), table_name='uploaded_files_version')
    op.drop_index(op.f('ix_uploaded_files_version_operation_type'), table_name='uploaded_files_version')
    op.drop_index(op.f('ix_uploaded_files_version_end_transaction_id'), table_name='uploaded_files_version')
    op.drop_index(op.f('ix_uploaded_files_version_created_at'), table_name='uploaded_files_version')
    op.drop_table('uploaded_files_version')
    # ### end Alembic commands ###
