"""add completed columns to activities

Revision ID: bbe568def046
Revises: a6f43936df79
Create Date: 2020-11-25 23:20:56.501151

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bbe568def046'
down_revision = 'a6f43936df79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('completed_by_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.execute("UPDATE activities SET is_complete = false")
    op.alter_column('activities', 'is_complete', nullable=False)
    op.create_foreign_key(None, 'activities', 'users', ['completed_by_id'], ['id'])
    op.add_column('activities_version', sa.Column('completed_at', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('activities_version', sa.Column('completed_by_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('activities_version', sa.Column('is_complete', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities_version', 'is_complete')
    op.drop_column('activities_version', 'completed_by_id')
    op.drop_column('activities_version', 'completed_at')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'is_complete')
    op.drop_column('activities', 'completed_by_id')
    op.drop_column('activities', 'completed_at')
    # ### end Alembic commands ###
