"""add custom fields property to cases

Revision ID: be275e7a5495
Revises: 4c04df3066b9
Create Date: 2020-05-12 17:51:27.388355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be275e7a5495'
down_revision = '4c04df3066b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('cases_version', sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases_version', 'custom_fields')
    op.drop_column('cases', 'custom_fields')
    # ### end Alembic commands ###
