"""add activities

Revision ID: bea0a35e6c0a
Revises: 740bd72ccc03
Create Date: 2020-09-29 17:51:21.021672

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bea0a35e6c0a'
down_revision = '740bd72ccc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('activity_definition_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True),
    sa.Column('created_location_position_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('created_location_altitude', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('created_location_altitude_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('created_location_heading', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('created_location_speed', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('created_location_dt', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), autoincrement=False, nullable=True),
    sa.Column('updated_location_position_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('updated_location_altitude', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('updated_location_altitude_accuracy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('updated_location_heading', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('updated_location_speed', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('updated_location_dt', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_activities_version_created_at'), 'activities_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_version_end_transaction_id'), 'activities_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_activities_version_operation_type'), 'activities_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_activities_version_transaction_id'), 'activities_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_activities_version_updated_at'), 'activities_version', ['updated_at'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_definition_id', sa.Integer(), nullable=False),
    sa.Column('custom_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('created_location_position_accuracy', sa.Float(), nullable=True),
    sa.Column('created_location_altitude', sa.Float(), nullable=True),
    sa.Column('created_location_altitude_accuracy', sa.Float(), nullable=True),
    sa.Column('created_location_heading', sa.Float(), nullable=True),
    sa.Column('created_location_speed', sa.Float(), nullable=True),
    sa.Column('created_location_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_location_coordinates', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('updated_location_position_accuracy', sa.Float(), nullable=True),
    sa.Column('updated_location_altitude', sa.Float(), nullable=True),
    sa.Column('updated_location_altitude_accuracy', sa.Float(), nullable=True),
    sa.Column('updated_location_heading', sa.Float(), nullable=True),
    sa.Column('updated_location_speed', sa.Float(), nullable=True),
    sa.Column('updated_location_dt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_definition_id'], ['activity_definitions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_updated_at'), 'activities', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_updated_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_activities_version_updated_at'), table_name='activities_version')
    op.drop_index(op.f('ix_activities_version_transaction_id'), table_name='activities_version')
    op.drop_index(op.f('ix_activities_version_operation_type'), table_name='activities_version')
    op.drop_index(op.f('ix_activities_version_end_transaction_id'), table_name='activities_version')
    op.drop_index(op.f('ix_activities_version_created_at'), table_name='activities_version')
    op.drop_table('activities_version')
    # ### end Alembic commands ###
