"""add mongo collection id to response

Revision ID: bf576353bfa4
Revises: 8ebc68288806
Create Date: 2019-12-03 02:36:08.570624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf576353bfa4'
down_revision = '8ebc68288806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('mongo_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'mongo_id')
    # ### end Alembic commands ###
