"""add reporting table name to case definitions

Revision ID: d83d6a1d4dd7
Revises: 61a072910ed4
Create Date: 2020-07-01 19:03:22.703018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83d6a1d4dd7'
down_revision = '61a072910ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_definitions', sa.Column('reporting_table_name', sa.String(length=64), nullable=True))
    op.add_column('case_definitions_version', sa.Column('reporting_table_name', sa.String(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_definitions_version', 'reporting_table_name')
    op.drop_column('case_definitions', 'reporting_table_name')
    # ### end Alembic commands ###
