"""remove custom_fields.selections

Revision ID: e5f98a847867
Revises: be275e7a5495
Create Date: 2020-05-14 17:32:06.134386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5f98a847867'
down_revision = 'be275e7a5495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_fields', 'selections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_fields', sa.Column('selections', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
