"""empty message

Revision ID: e6d95b2c7791
Revises: 8de105ff6059
Create Date: 2020-04-07 21:46:08.681237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d95b2c7791'
down_revision = '8de105ff6059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metabase_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['metabase_user_id'])
    op.add_column('users_version', sa.Column('metabase_user_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_version', 'metabase_user_id')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'metabase_user_id')
    # ### end Alembic commands ###
