"""add assigned to info to cases

Revision ID: f4215b318a25
Revises: 0de2fad69edb
Create Date: 2020-10-13 19:40:02.005223

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4215b318a25'
down_revision = '0de2fad69edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('cases', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['assigned_to_id'], ['id'])
    op.add_column('cases_version', sa.Column('assigned_at', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('cases_version', sa.Column('assigned_to_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases_version', 'assigned_to_id')
    op.drop_column('cases_version', 'assigned_at')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'assigned_to_id')
    op.drop_column('cases', 'assigned_at')
    # ### end Alembic commands ###
