# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20190930.0.0"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 5000, host: 5000 # Flask
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # Metabase

  # Customize VirtualBox VM
  config.vm.provider "virtualbox" do |v|
    v.name = "EPS API"
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.synced_folder ".", "/home/vagrant/app",
    id: "vagrant-root",
    owner: "vagrant",
    group: "vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y upgrade

    sudo apt-get install -y build-essential postgresql libpq-dev awscli \
      python-pip python3-pip python3-venv postgis jq
    pip3 install awsebcli
    pip3 install -U pip
    sudo -u postgres -- createuser -sU postgres vagrant
    sudo -u postgres -- createuser -sU postgres metabase_pg_user

    sudo -u postgres createdb api_pg
    sudo -u postgres createdb api_test_pg
    sudo -u postgres createdb data_pg
    sudo -u postgres createdb data_test_pg

    sudo -u postgres psql api_pg -c "CREATE EXTENSION postgis;"
    sudo -u postgres psql api_test_pg -c "CREATE EXTENSION postgis;"

    sudo -u postgres psql data_pg -c "ALTER USER metabase_pg_user WITH encrypted password 'securepassword1'"
    sudo -u postgres psql data_test_pg -c "ALTER USER metabase_pg_user WITH encrypted password 'securepassword1'"

    # create a postgresql database for metabase to use instead of the H2 default
    sudo -u postgres createdb metabase_pg
    sudo -u postgres psql metabase_pg -c "ALTER USER metabase_pg_user WITH encrypted password 'securepassword1'"

    # pgcli
    sudo apt-get -y install pgcli

    # java
    sudo apt -y install default-jre

    # get Metabase jar
    wget -P /home/vagrant/app/metabase "https://downloads.metabase.com/v0.35.4/metabase.jar"

  SHELL
end


